### ISSUE TITLE
Rake task does not load initializers

### ISSUE THREAD

**Issue by rylnd** [gonzalo-bulnes/dredd-rack#8]
Following the README for setting up dredd-rack, we end up with a rake task definition and an initializer file. However, the initializer is not run by the rake task, and thus `Dredd::Rack.app` is `nil` when the test runs, resulting in a 500 response and subsequent failures.

We happened to solve this by explicitly requiring the environment in the rake task:

```ruby
task dredd: :environment
```

I realize the documentation also recommends placing the assignment of `Dredd::Rack.app` in either app.rb or the Rakefile, but the standard location for that kind of thing seems like an initializer, so I would expect that to work as well.

Perhaps we missed something? Please advise.

**Comment by gonzalo-bulnes** [comment]
Hi @rylnd,

You are totally right, configuring _Dredd::Rack_ in an initializer is the natural thing to do in a Rails app, and it should be possible to make Dredd::Rack aware of that. I'll tag this issue as an **enhancement** with that purpose.

Besides, really many thanks for relating the server errors and the missing `:environment` prerequisite!
You made me realize that Rails applications were in fact never loaded correctly because their environment wasn't being loaded. (In fact the `config.ru` file of a Rails app do exactly that: load the environment, then start the app.)

I created a [Rails example application][rails] to make sure I don't miss something that big again and opened the [corresponding issue][bug]. I've a fix at hand, and should be able to release it tonight or tomorrow. I'll keep you updated.





  [bug]: https://github.com/gonzalo-bulnes/dredd-rack/issues/9
  [rails]: https://github.com/gonzalo-bulnes/dredd-rack-rails-example

**Comment by gonzalo-bulnes** [comment]
@rylnd 

I released Dredd::Rack **v0.5.0**. To get it, you only need to update you `Gemfile` and run `bundle update dredd-rack`. You should then be able to define the base `:dredd` task with `Dredd::Rack::RakeTask.new` as you first intended.

I look forward to your feedback!
Regards : )

**Comment by rylnd** [comment]
@gonzalo-bulnes thanks so much for the quick response!

0.5.0 didn't immediately fix things for us, but that's because of a separate issue: defining the Rake task in lib/tasks. I'll open a separate issue for that; 0.5.0 did in fact fix what I originally stated.

Thanks again!
